### ISSUE TITLE
Please Add a Project License

### ISSUE THREAD

**Issue by mcdonnnj** [patrickthomashansen/dorfromantik_helper#1]
As the title asks it would be great if you added a license for this project to make it clear what is allowed beyond that spelled out [in the GitHub documentation on repository licensing](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license).

**Comment by patrickthomashansen** [comment]
Added MIT license
